export const retailerList = [{
    label: 'United States',
    country: 'US',
    location: 'USD',
    code: 'amazon',
    domain: 'amazon.com',
    icon: 'USFlag',
    list: ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY']
  },
  // {
  //   label: 'United Kingdom',
  //   country: 'UK',
  //   location: 'GBP',
  //   code: 'amazon_uk',
  //   domain: 'amazon.co.uk',
  //   icon: 'UKFlag',
  //   list: [
  //     'I0',
  //     'I1',
  //     'I2',
  //     'I3',
  //     'I4',
  //     'I5',
  //     'I6',
  //     'I7',
  //     'I8',
  //     'I9',
  //     'IB',
  //     'IC',
  //     'IE',
  //     'IF',
  //     'IG',
  //     'IH',
  //     'II',
  //     'IJ',
  //     'IK',
  //     'IM',
  //     'IO',
  //     'IP',
  //     'IQ',
  //     'IR',
  //     'IS',
  //     'IT',
  //     'IU',
  //     'IV',
  //     'IW',
  //     'IX',
  //     'IY',
  //     'IZ',
  //     'J0',
  //     'J1',
  //     'J2',
  //     'J3',
  //     'J4',
  //     'J5',
  //     'J6',
  //     'J7',
  //     'J8',
  //     'J9',
  //     'JA',
  //     'JB',
  //     'JC',
  //     'JD',
  //     'JE',
  //     'JF',
  //     'JG',
  //     'JH',
  //     'JI',
  //     'JJ',
  //     'JK',
  //     'JL',
  //     'JM',
  //     'JN',
  //     'JO',
  //     'JP',
  //     'JQ',
  //     'JR',
  //     'JS',
  //     'JT',
  //     'JU',
  //     'JV',
  //     'JW',
  //     'JX',
  //     'HAW',
  //     'JY',
  //     'JZ',
  //     'K0',
  //     'K1',
  //     'K2',
  //     'K3',
  //     'K4',
  //     'K5',
  //     'K6',
  //     'K7',
  //     'K8',
  //     'K9',
  //     'KA',
  //     'KB',
  //     'KC',
  //     'KD',
  //     'KE',
  //     'KF',
  //     'KG',
  //     'KI',
  //     'KH',
  //     'KJ',
  //     'KK',
  //     'KL',
  //     'KM',
  //     'KN',
  //     'KP',
  //     'KQ',
  //     'KR',
  //     'KT',
  //     'KU',
  //     'KV',
  //     'KO',
  //     'KW',
  //     'KX',
  //     'KZ',
  //     'L0',
  //     'L1',
  //     'L2',
  //     'L3',
  //     'L4',
  //     'L5',
  //     'L6',
  //     'L7',
  //     'L8',
  //     'L9',
  //     'LB',
  //     'LC',
  //     'LD',
  //     'LE',
  //     'LF',
  //     'LG',
  //     'LH',
  //     'LI',
  //     'LJ',
  //     'LK',
  //     'LL',
  //     'LM',
  //     'LN',
  //     'LO',
  //     'LP',
  //     'LQ',
  //     'LR',
  //     'LS',
  //     'LT',
  //     'LU',
  //     'LV',
  //     'LW',
  //     'LX',
  //     'LY',
  //     'LZ',
  //     'M0',
  //     'M1',
  //     'M2',
  //     'M3',
  //     'M4',
  //     'M5',
  //     'M6',
  //     'M7'
  //   ],
  // },
  // {
  //   label: 'Canada',
  //   country: 'CA',
  //   location: 'CAD',
  //   code: 'amazon_ca',
  //   domain: 'amazon.ca',
  //   icon: 'CAFlag',
  //   list: ['AB', 'BC', 'MB', 'NB', 'NF', 'NT', 'NS', 'NU', 'ON', 'PE', 'QC', 'SK', 'YT']
  // },
  // {
  //   label: 'Germany',
  //   country: 'DE',
  //   location: 'EUR',
  //   code: 'amazon_de',
  //   domain: 'amazon.de',
  //   icon: 'DEFlag',
  //   list: ['BW', 'BY', 'BE', 'BB', 'HB', 'HH', 'HE', 'MV', 'NI', 'NW', 'RP', 'SL', 'SN', 'ST', 'SH', 'TH'],
  // },
  // {
  //   label: 'Mexico',
  //   country: 'MX',
  //   location: 'MXN',
  //   code: 'amazon_mx',
  //   domain: 'amazon.com.mx',
  //   icon: 'MXFlag',
  //   list: ['AG', 'BN', 'BS', 'CH', 'CI', 'CL', 'CP', 'CS', 'DF', 'DG', 'GE', 'GJ', 'HD', 'JA', 'MC', 'MR', 'MX', 'NA', 'NL', 'OA', 'PU', 'QE', 'QI', 'SI', 'SL', 'SO', 'TA', 'TB', 'TL', 'VC', 'YU', 'ZA'],
  // },
];